import { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../contexts/AuthContext';
import { PieChart, Pie, Cell, ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';

const COLORS = ['#10b981', '#3b82f6', '#f59e0b', '#6366f1', '#ef4444', '#8b5cf6'];

const PRESETS = [
  { label: 'Last Week', days: 7 },
  { label: 'Last Month', days: 30 },
  { label: 'Last 3 Months', days: 90 },
  { label: 'Last 6 Months', days: 180 },
  { label: 'Last Year', days: 365 },
  { label: 'Custom Range', days: 0 }
];

export default function TimeTravel() {
  const { token } = useAuth();
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const [summary, setSummary] = useState('');
  const [analysisData, setAnalysisData] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [selectedPreset, setSelectedPreset] = useState(0);

  useEffect(() => {
    // Set default to last month
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(endDate.getDate() - 30);

    setStart(startDate.toISOString().split('T')[0]);
    setEnd(endDate.toISOString().split('T')[0]);
  }, []);

  const applyPreset = (preset: typeof PRESETS[0], index: number) => {
    setSelectedPreset(index);
    if (preset.days > 0) {
      const endDate = new Date();
      const startDate = new Date();
      startDate.setDate(endDate.getDate() - preset.days);

      setStart(startDate.toISOString().split('T')[0]);
      setEnd(endDate.toISOString().split('T')[0]);
    }
  };

  const generateSummary = async () => {
    if (!start || !end) return;

    setLoading(true);
    try {
      const res = await axios.post('/insights/summary',
        { start, end },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      setSummary(res.data.aiSummary || res.data.summary || 'No summary available');
      setAnalysisData(res.data.analysisData);
    } catch (e) {
      console.error('Failed to generate summary', e);
      setSummary('Error generating summary. Please try again.');
      setAnalysisData(null);
    } finally {
      setLoading(false);
    }
  };

  const exportSummary = () => {
    const content = `
Time Travel Summary: ${start} to ${end}

${summary}

Analysis Data:
- Total Entries: ${analysisData?.totalEntries || 0}
- Average Words per Entry: ${analysisData?.avgWordsPerEntry || 0}
- Emotions: ${Object.entries(analysisData?.emotions || {}).map(([k, v]) => `${k}: ${v}`).join(', ')}
- Keywords: ${Object.keys(analysisData?.keywords || {}).join(', ')}

Generated by Memoir AI - ${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `memoir-reflection-${start}-to-${end}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const emotionData = analysisData ? Object.entries(analysisData.emotions).map(([name, value]) => ({ name, value })) : [];
  const sentimentData = analysisData ? [
    { name: 'Positive', value: analysisData.sentiments.positive },
    { name: 'Neutral', value: analysisData.sentiments.neutral },
    { name: 'Negative', value: analysisData.sentiments.negative }
  ].filter(item => item.value > 0) : [];

  return (
    <div className="p-6 max-w-6xl mx-auto flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Time Travel Reflections</h1>
        <div className="text-sm text-gray-600 dark:text-gray-400">
          Reflect on your mental wellness journey over time
        </div>
      </div>

      {/* Date Selection */}
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm">
        <h2 className="text-lg font-semibold mb-4">Select Time Period</h2>

        {/* Preset Buttons */}
        <div className="flex flex-wrap gap-2 mb-4">
          {PRESETS.map((preset, index) => (
            <button
              key={preset.label}
              onClick={() => applyPreset(preset, index)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                selectedPreset === index
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
              }`}
            >
              {preset.label}
            </button>
          ))}
        </div>

        {/* Custom Date Inputs */}
        <div className="flex gap-4 items-center">
          <div className="flex items-center gap-2">
            <label className="text-sm font-medium">From:</label>
            <input
              type="date"
              className="px-3 py-2 rounded border bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              value={start}
              onChange={e => setStart(e.target.value)}
            />
          </div>
          <div className="flex items-center gap-2">
            <label className="text-sm font-medium">To:</label>
            <input
              type="date"
              className="px-3 py-2 rounded border bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              value={end}
              onChange={e => setEnd(e.target.value)}
            />
          </div>
          <button
            className="ml-auto px-6 py-2 rounded bg-blue-600 text-white font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            onClick={generateSummary}
            disabled={loading || !start || !end}
          >
            {loading ? 'Generating...' : 'Generate Reflection'}
          </button>
        </div>
      </div>

      {/* Summary Display */}
      {summary && (
        <div className="bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 rounded-lg p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold flex items-center gap-2">
              AI Reflection Summary
            </h2>
            <button
              onClick={exportSummary}
              className="px-4 py-2 rounded bg-green-600 text-white text-sm font-medium hover:bg-green-700"
            >
              Export Summary
            </button>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line">{summary}</p>
          </div>
        </div>
      )}

      {/* Analysis Dashboard */}
      {analysisData && (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Period Stats */}
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm">
            <h3 className="font-semibold mb-4">
              Period Overview
            </h3>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-sm text-gray-600 dark:text-gray-400">Total Entries</span>
                <span className="font-semibold">{analysisData.totalEntries}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-gray-600 dark:text-gray-400">Avg Words/Entry</span>
                <span className="font-semibold">{analysisData.avgWordsPerEntry}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-gray-600 dark:text-gray-400">Date Range</span>
                <span className="font-semibold text-sm">{start} to {end}</span>
              </div>
            </div>
          </div>

          {/* Emotion Distribution */}
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm">
            <h3 className="font-semibold mb-4">
              Emotional Landscape
            </h3>
            {emotionData.length > 0 ? (
              <div className="h-48">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={emotionData}
                      dataKey="value"
                      nameKey="name"
                      outerRadius={70}
                      label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                    >
                      {emotionData.map((entry: any, index: number) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            ) : (
              <p className="text-gray-500 text-sm">No emotion data available</p>
            )}
          </div>

          {/* Sentiment Timeline */}
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm">
            <h3 className="font-semibold mb-4">
              Sentiment Overview
            </h3>
            {sentimentData.length > 0 ? (
              <div className="space-y-2">
                {sentimentData.map((item: any) => (
                  <div key={item.name} className="flex justify-between items-center">
                    <span className="text-sm capitalize">{item.name}</span>
                    <div className="flex items-center gap-2">
                      <div className="w-16 bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                        <div
                          className={`h-2 rounded-full ${
                            item.name === 'Positive' ? 'bg-green-500' :
                            item.name === 'Negative' ? 'bg-red-500' : 'bg-yellow-500'
                          }`}
                          style={{ width: `${(item.value / analysisData.totalEntries) * 100}%` }}
                        ></div>
                      </div>
                      <span className="text-sm font-semibold w-8 text-right">{item.value}</span>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-gray-500 text-sm">No sentiment data available</p>
            )}
          </div>

          {/* Key Topics */}
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm md:col-span-2 lg:col-span-3">
            <h3 className="font-semibold mb-4">
              Key Topics & Keywords
            </h3>
            {Object.keys(analysisData.keywords).length > 0 ? (
              <div className="flex flex-wrap gap-2">
                {Object.entries(analysisData.keywords)
                  .sort(([,a]: any, [,b]: any) => b - a)
                  .slice(0, 20)
                  .map(([keyword, count]: [string, any]) => (
                    <span
                      key={keyword}
                      className="px-3 py-1 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 rounded-full text-sm"
                      title={`${keyword}: ${count} occurrences`}
                    >
                      {keyword} ({count})
                    </span>
                  ))}
              </div>
            ) : (
              <p className="text-gray-500 text-sm">No keywords extracted</p>
            )}
          </div>
        </div>
      )}

      {!summary && !loading && (
        <div className="text-center py-12">
          <div className="text-6xl mb-4">🕰️</div>
          <h3 className="text-xl font-semibold mb-2">Ready to Reflect?</h3>
          <p className="text-gray-600 dark:text-gray-400">
            Select a time period above and generate an AI-powered reflection of your mental wellness journey.
          </p>
        </div>
      )}
    </div>
  );
}


